baseURL: https://example.com
title: RLet
theme: hugo-theme-m10c
paginate: 5
publishDir: "docs/"
menu:
  main:
    - identifier: home
      name: Home
      url: /home/
    - identifier: tags
      name: Tags
      url: /tags/
params:
  author: John Doe
  description: Tentando criar um blog via R [versão 178]
  menu_item_separator: ' - '
  social:
    - name: github
      url: https://github.com/gohugoio
    - name: linkedin
      url: https://twitter.com/gohugoio
