baseURL: https://lodthomaz.github.io/RLet_dois/
title: RLet
theme: hugo-theme-m10c
paginate: 5
publishDir: "docs/"
menu:
  main:
    - identifier: home
      name: Home
      url: /home/
    - identifier: tags
      name: Tags
      url: /tags/
params:
  author: John Doe
  description: Tentando criar um blog via R e tentando alterar a cor !!! [versão 178 - agora vai]
  menu_item_separator: ' - '
  social:
    - name: github
      url: https://github.com/lodthomaz/
    - name: linkedin
      url: https://www.linkedin.com/in/leticiathomaz/
params.style:
  darkestColor: "#463625"
  darkColor: "#2a3738"
  primaryColor: "#eeee6a"
  lightColor: "#96a879"
  lightestColor: "#ffffff"